# Generated by Django 3.1.12 on 2021-08-23 07:52

from django.db import migrations


def init_user_msg_subscription(apps, schema_editor):
    UserMsgSubscription = apps.get_model('notifications', 'UserMsgSubscription')
    User = apps.get_model('users', 'User')
    from notifications.backends import BACKEND

    to_create = []
    users = User.objects.all()
    for user in users:
        receive_backends = []
        for backend in BACKEND:
            if backend.get_account(user):
                receive_backends.append(backend)
        to_create.append(UserMsgSubscription(user=user, receive_backends=receive_backends))
    UserMsgSubscription.objects.bulk_create(to_create)
    print(f'\n  Init user message subscription: {len(to_create)}')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_feishu_id'),
        ('notifications', '0002_auto_20210823_1619'),
    ]

    operations = [
        migrations.RunPython(init_user_msg_subscription)
    ]
